Garopi\LegacyWrapperBundle\Entity\Articles:
    type: entity
    table: articles
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 255
            fixed: false
        content:
            type: text
            nullable: true
            length: null
            fixed: false
        categoryId:
            type: integer
            nullable: true
            unsigned: false
            column: category_id
        userId:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: user_id
        pictureFileName:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: picture_file_name
        pictureContentType:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: picture_content_type
        pictureFileSize:
            type: integer
            nullable: true
            unsigned: false
            column: picture_file_size
        pictureUpdatedAt:
            type: string
            nullable: true
            column: picture_updated_at
        createdAt:
            type: string
            nullable: false
            column: created_at
        updatedAt:
            type: string
            nullable: false
            column: updated_at
        summary:
            type: text
            nullable: true
            length: null
            fixed: false
        author:
            type: string
            nullable: true
            length: 255
            fixed: false
        hidden:
            type: boolean
            nullable: true
            default: t
    lifecycleCallbacks: {  }
